# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mapRIOSettings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(408, 251)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(220, 210, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 351, 181))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 331, 145))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 2, 1, 1)
        self.mapROIRot = QtWidgets.QLineEdit(self.layoutWidget)
        self.mapROIRot.setObjectName("mapROIRot")
        self.gridLayout.addWidget(self.mapROIRot, 4, 3, 1, 1)
        self.mapROIXStart = QtWidgets.QLineEdit(self.layoutWidget)
        self.mapROIXStart.setObjectName("mapROIXStart")
        self.gridLayout.addWidget(self.mapROIXStart, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 2, 1, 1)
        self.mapROIYEnd = QtWidgets.QLineEdit(self.layoutWidget)
        self.mapROIYEnd.setObjectName("mapROIYEnd")
        self.gridLayout.addWidget(self.mapROIYEnd, 2, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.mapROIXEnd = QtWidgets.QLineEdit(self.layoutWidget)
        self.mapROIXEnd.setObjectName("mapROIXEnd")
        self.gridLayout.addWidget(self.mapROIXEnd, 2, 1, 1, 1)
        self.mapROIYStart = QtWidgets.QLineEdit(self.layoutWidget)
        self.mapROIYStart.setObjectName("mapROIYStart")
        self.gridLayout.addWidget(self.mapROIYStart, 1, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.mapROIZ = QtWidgets.QLineEdit(self.layoutWidget)
        self.mapROIZ.setObjectName("mapROIZ")
        self.gridLayout.addWidget(self.mapROIZ, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.mapROIXStart, self.mapROIXEnd)
        Dialog.setTabOrder(self.mapROIXEnd, self.mapROIYStart)
        Dialog.setTabOrder(self.mapROIYStart, self.mapROIYEnd)
        Dialog.setTabOrder(self.mapROIYEnd, self.mapROIZ)
        Dialog.setTabOrder(self.mapROIZ, self.mapROIRot)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Mapping ROI Settings"))
        self.groupBox.setTitle(_translate("Dialog", "ROI Definition (Whole scan Area definition)"))
        self.label_7.setText(_translate("Dialog", "Rotation"))
        self.label_4.setText(_translate("Dialog", "Y start"))
        self.label_5.setText(_translate("Dialog", "Y end"))
        self.label_6.setText(_translate("Dialog", "Z"))
        self.label_2.setText(_translate("Dialog", "X start"))
        self.label_3.setText(_translate("Dialog", "X end"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
