# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'samplesposition.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(429, 307)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(340, 20, 81, 61))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.samplepositions = QtWidgets.QTableWidget(Dialog)
        self.samplepositions.setGeometry(QtCore.QRect(10, 20, 321, 271))
        self.samplepositions.setObjectName("samplepositions")
        self.samplepositions.setColumnCount(3)
        self.samplepositions.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.samplepositions.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.samplepositions.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.samplepositions.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.samplepositions.setHorizontalHeaderItem(2, item)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Sample positions"))
        item = self.samplepositions.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.samplepositions.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "X"))
        item = self.samplepositions.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Y"))
        item = self.samplepositions.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Sample Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
